name = "r2-list-items"
type = "javascript"

account_id = ACCOUNT_ID
workers_dev = true
compatibility_date = "2023-02-26"

[build.upload]
format = "modules"
dir = "./src"
main = "./index.mjs"



[[r2_buckets]]
bucket_name = BUCKET
binding = "MY_BUCKET"